<?php

namespace AppBundle\Repository;

/**
 * ChampsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampsRepository extends \Doctrine\ORM\EntityRepository
{
}
