<?php

namespace AppBundle\Repository;

/**
 * GroupesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupesRepository extends \Doctrine\ORM\EntityRepository
{
}
