<?php

namespace AppBundle\Repository;

/**
 * TemplatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplatesRepository extends \Doctrine\ORM\EntityRepository
{
}
